apiVersion: apps/v1
kind: Deployment
metadata:
  name: ott-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ott-app
  template:
    metadata:
      labels:
        app: ott-app
    spec:
      containers:
      - name: ott-app
        image: amithachar/ott-app:latest
        ports:
        - containerPort: 8000
